version: "3.8"

services:
  book-service:
    build:
      context: ./book-service
    ports:
      - "8081:8080"
  author-service:
    build:
      context: ./author-service
    ports:
      - "8082:8080"
  category-service:
    build:
      context: ./category-service
    ports:
      - "8083:8080"
  user-service:
    build:
      context: ./user-service
    ports:
      - "8084:8080"

  borrowing-service:
    build:
      context: ./user-service
    ports:
      - "8085:8080"
